"""Assemble a downloadable project from the agents' phase outputs.

Different agents emit files under different keys — backend/frontend use
`files: [{path, code}]`, QA uses `test_files`, DevOps uses `dockerfiles` /
`compose_or_manifests` / `ci_cd` with `content`. Rather than special-casing each,
we generically treat *any* list of `{path, code|content}` objects as files.
"""
from __future__ import annotations

import io
import re
import zipfile
from typing import Iterator, Tuple

from app.core.constants import PHASE_LABELS
from app.db.models import Project


def _iter_files(output: dict) -> Iterator[Tuple[str, str, str]]:
    """Yield (path, content, language) for every file-like item in an agent output."""
    if not isinstance(output, dict):
        return
    for value in output.values():
        if not isinstance(value, list):
            continue
        for item in value:
            if not isinstance(item, dict):
                continue
            path = item.get("path")
            content = item.get("code") or item.get("content")
            if isinstance(path, str) and path.strip() and isinstance(content, str) and content.strip():
                lang = item.get("language") or item.get("framework") or item.get("tool") or ""
                yield path.strip().lstrip("/"), content, lang


def assemble(project: Project) -> dict:
    """Collapse all phases into deduped files + docs + setup instructions."""
    files: dict[str, dict] = {}  # path -> record (later phases win)
    setup: list[str] = []
    docs: list[dict] = []

    for ph in project.phases:
        out = ph.output if isinstance(ph.output, dict) else {}
        for path, content, lang in _iter_files(out):
            files[path] = {"path": path, "content": content, "language": lang, "phase": ph.phase}

        instructions = out.get("setup_instructions")
        if isinstance(instructions, list):
            for step in instructions:
                if isinstance(step, str) and step.strip() and step not in setup:
                    setup.append(step.strip())

        if ph.content_md:
            docs.append(
                {
                    "path": f"docs/{ph.phase}.md",
                    "title": PHASE_LABELS.get(ph.phase, ph.phase),
                    "content": ph.content_md,
                }
            )

    return {"files": sorted(files.values(), key=lambda f: f["path"]), "setup_instructions": setup, "docs": docs}


def readme_md(project: Project, assembled: dict) -> str:
    lines = [
        f"# {project.name or project.idea}",
        "",
        f"> {project.idea}",
        "",
        "Generated by the **AI Software Engineering Team** — a multi-agent build pipeline.",
        "",
    ]
    if assembled["setup_instructions"]:
        lines += ["## Setup", ""]
        lines += [f"{i}. {s}" for i, s in enumerate(assembled["setup_instructions"], 1)]
        lines.append("")
    if assembled["files"]:
        lines += ["## Generated files", ""]
        lines += [
            f"- `{f['path']}`" + (f" — {f['language']}" if f["language"] else "")
            for f in assembled["files"]
        ]
        lines.append("")
    if assembled["docs"]:
        lines += ["## Documentation", ""]
        lines += [f"- `{d['path']}` — {d['title']}" for d in assembled["docs"]]
        lines.append("")
    return "\n".join(lines)


def slug(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_-]+", "-", (text or "project")[:48]).strip("-").lower()
    return s or "project"


def build_zip(project: Project, assembled: dict) -> bytes:
    """A real, unzippable project archive: README + code files + docs."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.md", readme_md(project, assembled))
        for f in assembled["files"]:
            z.writestr(f["path"], f["content"])
        for d in assembled["docs"]:
            z.writestr(d["path"], d["content"])
    return buf.getvalue()
