"""Publish a generated project to a user's own GitHub account.

The OAuth "Connect" flow gives us a short-lived access token that belongs to the
*user* who authorized (not the operator). With it we create a brand-new repo on
their account and push every generated file in a single commit via the Git Data
API — blobs are created inline by the tree endpoint, so one tree + one commit +
one ref update is all it takes.

Tokens are never persisted here; the route layer keeps them in a per-browser
session and hands one in per call.
"""
from __future__ import annotations

from typing import Optional

import httpx

from app.core import artifacts
from app.core.config import settings
from app.db.models import Project

_API = "https://api.github.com"
_TIMEOUT = 30.0


class GitHubError(Exception):
    """A user-facing problem talking to GitHub (surfaced as a clean 400)."""


# ── OAuth ────────────────────────────────────────────────────────────────────
def exchange_code(code: str) -> str:
    """Trade an OAuth `code` for the user's access token."""
    r = httpx.post(
        "https://github.com/login/oauth/access_token",
        data={
            "client_id": settings.github_client_id,
            "client_secret": settings.github_client_secret,
            "code": code,
        },
        headers={"Accept": "application/json"},
        timeout=_TIMEOUT,
    )
    r.raise_for_status()
    data = r.json()
    token = data.get("access_token")
    if not token:
        raise GitHubError(
            data.get("error_description") or "GitHub did not return an access token."
        )
    return token


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_user(token: str) -> dict:
    """The authenticated user's public profile (login / name / avatar)."""
    r = httpx.get(f"{_API}/user", headers=_headers(token), timeout=_TIMEOUT)
    r.raise_for_status()
    return r.json()


# ── Push ─────────────────────────────────────────────────────────────────────
def _gather_files(project: Project) -> dict[str, str]:
    """The exact same fileset the .zip download contains: README + code + docs."""
    assembled = artifacts.assemble(project)
    files: dict[str, str] = {"README.md": artifacts.readme_md(project, assembled)}
    for f in assembled["files"]:
        files[f["path"]] = f["content"]
    for d in assembled["docs"]:
        files[d["path"]] = d["content"]
    return files


def push_project(
    token: str,
    project: Project,
    name: Optional[str] = None,
    private: bool = True,
    description: Optional[str] = None,
) -> dict:
    """Create a repo on the user's account and push the whole project to it."""
    files = _gather_files(project)
    if not files:
        raise GitHubError("This project has no generated files to push yet.")

    repo_name = artifacts.slug(name or project.name or project.idea)
    desc = (description or project.idea or "")[:300] or (
        "Generated by the AI Software Engineering Team"
    )
    h = _headers(token)

    # 1. Create the repo. auto_init gives us a default branch + base commit to
    #    build on (its starter README is replaced by our fresh tree below).
    r = httpx.post(
        f"{_API}/user/repos",
        headers=h,
        timeout=_TIMEOUT,
        json={
            "name": repo_name,
            "private": private,
            "description": desc,
            "auto_init": True,
        },
    )
    if r.status_code == 422:
        raise GitHubError(
            f"You already have a repository named '{repo_name}'. "
            "Choose a different name and try again."
        )
    if r.status_code not in (200, 201):
        raise GitHubError(f"GitHub could not create the repo ({r.status_code}): {r.text[:200]}")
    repo = r.json()
    full = repo["full_name"]
    branch = repo.get("default_branch") or "main"

    # 2. Base commit SHA of the freshly-initialised branch.
    ref = httpx.get(f"{_API}/repos/{full}/git/ref/heads/{branch}", headers=h, timeout=_TIMEOUT)
    ref.raise_for_status()
    base_sha = ref.json()["object"]["sha"]

    # 3. One tree from all our files (the tree API inlines blob creation).
    tree = [
        {"path": path, "mode": "100644", "type": "blob", "content": content}
        for path, content in files.items()
    ]
    tr = httpx.post(f"{_API}/repos/{full}/git/trees", headers=h, timeout=_TIMEOUT, json={"tree": tree})
    if tr.status_code not in (200, 201):
        raise GitHubError(f"GitHub could not build the file tree ({tr.status_code}): {tr.text[:200]}")
    tree_sha = tr.json()["sha"]

    # 4. Commit pointing at the new tree, parented to the base commit.
    cm = httpx.post(
        f"{_API}/repos/{full}/git/commits",
        headers=h,
        timeout=_TIMEOUT,
        json={
            "message": "Initial commit — generated by the AI Software Engineering Team",
            "tree": tree_sha,
            "parents": [base_sha],
        },
    )
    cm.raise_for_status()
    commit_sha = cm.json()["sha"]

    # 5. Fast-forward the branch to our commit.
    up = httpx.patch(
        f"{_API}/repos/{full}/git/refs/heads/{branch}",
        headers=h,
        timeout=_TIMEOUT,
        json={"sha": commit_sha, "force": True},
    )
    up.raise_for_status()

    return {
        "html_url": repo["html_url"],
        "full_name": full,
        "branch": branch,
        "private": bool(repo.get("private")),
        "files": len(files),
    }
